src/app/(testPages)/modal/page.tsx, src/app/globals.css, src/components/Modal.tsx, src/components/Popup.tsx, src/types/components/modalPopup.d.ts
[MNM-17]
http://localhost:3000/modal
https://wild-egg-9ad.notion.site/99846cb28a9d40ca869a0e86113fddb0
[MNM-17]: https://daremfit.atlassian.net/browse/MNM-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-17]feat: 공용컴포넌트 모달,팝업 구현

tailwind.config.ts
> MNM-22
> 브레이크 포인트 설정 했습니다.
> tablet : 768px desktop: 1200px
=> [MNM-22]chore: tailwind setting

.prettierrc.js
> MNM-26
> import 정렬 방법 수정했습니다
=> [MNM-26]fix: pretierr에서 폴더 정렬 수정

.husky/post-commit
> MNM-27
> 커밋이후 fetch 및 rebase 하는 허스키를 추가했습니다.
> 충돌 발생시 수기로 해결하면 됩니다.
=> [MNM-27]chore: post-commit husky 추가

src/apis/method/delete.ts, src/apis/method/get.ts, src/apis/method/postPut.ts
[MNM-21]
추후에 env 넣어서 서버 주소 넣어야하며 문제 있을 시에 수정하여 사용하시면 되겠습니다.
https://www.notion.so/99846cb28a9d40ca869a0e86113fddb0
[MNM-21]: https://daremfit.atlassian.net/browse/MNM-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-21]feat: api통신 함수구현(get,post&put,delete)

package-lock.json, package.json, src/app/(testPages)/progressbar/page.tsx, src/components/Progressbar.tsx
[MNM-25]
프로그레스바 기능구현
div같은 태그로 한칸 감싸주시면 그에 맞는 크기가 될 겁니다.
``` 
npm install framer-motion
```
사용방법
https://www.notion.so/99846cb28a9d40ca869a0e86113fddb0
[MNM-25]: https://daremfit.atlassian.net/browse/MNM-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-25]feat: 프로그레스바기능구현

src/app/(sign)/signup/page.tsx
> MNM-33
> 회원가입 input 입니다.. api가 아직 정확하지 않아서 비워두었습니다.
> 추후 api 연결 및 popup 추가 예정입니다.
> 버튼도 임시로 넣은거라 추후 조환님이 만든 버튼으로 변경예정입니다.
> nav 수정시 mt 줬던거 삭제 예정입니다.
=> [MNM-33]feat: 회원가입 input 작성

tailwind.config.ts
> MNM-37
> tailwind 색상 추가했습니다.
=> [MNM-37]refactor: tailwind config 수정

src/apis/authApi.ts, src/apis/fetchInstance.ts, src/apis/gatheringsApi.ts, src/apis/reviewsApi.ts, src/app/(testPages)/(apis)/testgathering/page.tsx
> MNM-43
> 크게 변경한건 없습니다.  사실 변경점은 AuthApi 폴더보면 끝입니다.
=> [MNM-43]refactor:api type 및 스웨거 변경사항수정 

src/apis/ApiError.ts, src/apis/HttpClient/HttpClient.ts, src/apis/HttpClient/error.ts, src/apis/authApi.ts, src/apis/fetchInstance.ts, src/app/actions/auth.ts
> MNM-47
> 인터셉터 기능 구현했습니다.
> 자세한 설명은 집에가서
=> [MNM-47]feat:intercepter

src/app/(testPages)/button/page.tsx, src/app/(testPages)/date/page.tsx, src/components/Button/Button.tsx, src/components/Button/LinkButton.tsx, src/components/Button/buttonStyles.ts, src/types/components/button.d.ts
> MNM-57
> 버튼에 hover 추가 기본 값 추가
=> [MNM-57]refactor: button

src/app/layout.tsx
> MNM-65
> 폰트 수정했습니다. inter -> pretendard
=> [MNM-65]feat: font 수정

package-lock.json, package.json, src/app/layout.tsx, src/app/providers.tsx
=> [MNM-68]feat: react query 추가

src/apis/assignGatheringApi.ts, src/apis/authApi.ts, src/apis/favoriteGatheringApi.ts, src/apis/reviewsApi.ts, src/apis/searchGatheringApi.ts, src/app/(testPages)/(apis)/testgathering/page.tsx, src/types/api/gatheringApi.d.ts, src/types/api/reviews.d.ts
=> [MNM-67] refactor: api

src/apis/assignGatheringApi.ts, src/app/(testPages)/(apis)/testgathering/create/page.tsx, src/app/(testPages)/(apis)/testgathering/page.tsx
=> [MNM-74]fix: createAPI 수정

next.config.mjs, src/apis/fetchInstance.ts
=> [MNM-78]chore: 프록시 서버로 임시 변경

src/store/userStore.ts
> MNM-79
> 로그인시 유저 데이터 로컬에 넣게 만들었습니다~
=> [MNM-79]refactor: 로그인시 유저데이터 로컬에 저장

next.config.mjs, src/apis/fetchInstance.ts, src/store/userStore.ts
=> [MNM-78]chore: nextconfig 원복

src/apis/HttpClient/HttpClient.ts, src/apis/authApi.ts, src/apis/fetchInstance.ts, src/app/(auth)/signin/page.tsx, src/app/actions/auth.ts, src/app/api/auth/signin/route.ts
> [MNM-83]
> 로그인시 유저데이터 전역상태관리에 저장
[MNM-83]: https://daremfit.atlassian.net/browse/MNM-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-83]fix: 로그인시 유저데이터 로컬에 저장

src/app/reviews/_components/RatingComponent.tsx, src/app/reviews/_components/ReviewCard.tsx, src/app/reviews/_components/ReviewListComponent.tsx, src/components/Filter/FilterDropDown.tsx, src/types/components/filter.d.ts
> [MNM-63]
> 카드 컴포넌트 조환님꺼 그냥 그대로 가지고왔습니다.
> 필터 드롭다운은 기존 방식으로 그냥 원상복구 시켰습니다. 
[MNM-63]: https://daremfit.atlassian.net/browse/MNM-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-63]refactor: 목데이터 삭제, 카드 컴포넌트 추가

src/app/(auth)/signin/page.tsx, src/app/(auth)/signup/page.tsx
> [MNM-86]
> 컴포넌트 밖에 href 가 있어서 배포주소에서는 못읽더라구요...그래서 컴포넌트 안으로 넣었습니다.
[MNM-86]: https://daremfit.atlassian.net/browse/MNM-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-86]fix: social리다이렉트 에러수정

src/components/Calendar/Calendar.tsx, src/components/Calendar/DropdownCalendar.tsx
MNM-35
> 캘린더 컴포넌트 한국 날짜로 변경해서 저장되게 수정했습니다.
=> [MNM-35] fix: 캘린더 컴포넌트 한국 날짜로 변경

src/app/api/auth/signin/route.ts
> [MNM-89]
[MNM-89]: https://daremfit.atlassian.net/browse/MNM-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-89]fix: login error 수정

src/app/groupDetail/_components/GroupDetail.tsx, src/components/ClosingTimeTag.tsx, src/utils/date.ts
MNM-91
이미지에 사용 할 마감시간 태그를 공통 컴포넌트로 구현했습니다.
radius는 일단 왼쪽 아래에만 해놨습니다.
className도 prop으로 받아서 추가 스타일 변경 가능합니다.
=> [MNM-91] feat: 마감시간 태그 컴포넌트 구현

src/app/api/gatherings/[id]/cancel/route.ts, src/app/api/gatherings/[id]/favorite/route.ts, src/app/api/gatherings/[id]/join/route.ts, src/app/api/gatherings/[id]/leave/route.ts, src/app/api/gatherings/[id]/route.ts, src/app/api/gatherings/favorite/route.ts, src/app/api/gatherings/joined/route.ts, src/app/api/gatherings/route.ts, src/app/api/my/gathering/route.ts, src/app/api/reviews/route.ts, src/app/api/user/route.ts
>[MNM-84]
> 엑세스 토큰없을시  Authorization: `Beare ` 로 가 에러가 발생했습니다.
> 엑세스 토큰이 존재 하지 않을시 Authorization를 보내지 않게 변경했습니다
[MNM-84]: https://daremfit.atlassian.net/browse/MNM-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-84]fix: 엑세스 토큰없을시 언디파인으로 가던거 수정

src/components/Button/FavoriteButton.tsx, src/components/Gnb.tsx, src/store/userStore.ts
>[MNM-103]
>GNB의 찜한 목록 탭 옆에 찜한 목록 개수 표시 추가
[MNM-103]: https://daremfit.atlassian.net/browse/MNM-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-103] feat: GNB 찜한 목록 개수 표시 기능

src/components/Gnb.tsx
> [MNM-127]
> GNB 인풋 요소 제거 요청 수행.
[MNM-127]: https://daremfit.atlassian.net/browse/MNM-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-127] refactor: GNB 검색바 2개 중 1개 요소 제거

src/app/api/auth/socialSignin/route.ts
=> [MNM-137]hotfix: social 수정

src/apis/assignGatheringApi.ts, src/app/api/gatherings/[id]/route.ts
=> [MNM-142]fix: 모임 수정 오류 수정

src/app/reviews/_components/AllReviews.tsx, src/app/reviews/_components/ReviewCard.tsx
>[MNM-147] 
> 기본 이미지 추가
> 이미지 클릭시 모임상세 이동
> 프로필 이미지 변경
> 메인 로고 이미지 변경
[MNM-147]: https://daremfit.atlassian.net/browse/MNM-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MNM-147] refactor: all reviews

src/app/groupDetail/_components/EditGathering.tsx, src/app/groupDetail/_components/FixedBottomBar.tsx, src/app/groupDetail/_components/Reviews.tsx, src/app/mypage/utils/MyCreatedGathering.tsx, src/components/MypageCard/MypageCard.tsx, src/components/MypageCard/ReviewCard.tsx
> MNM-122
> 모임카드 클릭 시 상세페이지로 라우팅
> 모임 디폴트이미지 변경
=> [MNM-122] refactor: 모임카드 상세페이지로 라우팅

src/app/groupDetail/_components/DetailCard.tsx, src/app/groupDetail/_components/FixedBottomBar.tsx, src/app/groupDetail/_components/GroupDetail.tsx, src/app/groupDetail/_components/Reviews.tsx
> MNM-41
> 상세페이지 프로필이미지 배경이미지로 변경
=> [MNM-41] refactor: 프로필이미지 배경이미지로 변경
